apiVersion: v1
kind: Service
metadata:
  name: goserver-service-nodeport
spec:
  selector: 
    app: goserver
  type: NodePort
  ports: 
  - name: goserver-service-nodeport
    port: 80
    targetPort: 8000 
    protocol: TCP
    nodePort: 30001 #30000 - 32767